// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.41537 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>IceCatXmlAccess</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IcecatSharp.XdsModels
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class body : System.ComponentModel.INotifyPropertyChanged
    {

        private filesindex filesindexField;

        public body()
        {
            this.filesindexField = new filesindex();
        }

        public filesindex filesindex
        {
            get
            {
                return this.filesindexField;
            }
            set
            {
                if ((this.filesindexField != null))
                {
                    if ((filesindexField.Equals(value) != true))
                    {
                        this.filesindexField = value;
                        this.OnPropertyChanged("filesindex");
                    }
                }
                else
                {
                    this.filesindexField = value;
                    this.OnPropertyChanged("filesindex");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class filesindex : System.ComponentModel.INotifyPropertyChanged
    {

        private List<file> fileField;

        private int generatedField;

        public filesindex()
        {
            this.fileField = new List<file>();
        }

        public List<file> file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                if ((this.fileField != null))
                {
                    if ((fileField.Equals(value) != true))
                    {
                        this.fileField = value;
                        this.OnPropertyChanged("file");
                    }
                }
                else
                {
                    this.fileField = value;
                    this.OnPropertyChanged("file");
                }
            }
        }

        public int Generated
        {
            get
            {
                return this.generatedField;
            }
            set
            {
                if ((generatedField.Equals(value) != true))
                {
                    this.generatedField = value;
                    this.OnPropertyChanged("Generated");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class file : System.ComponentModel.INotifyPropertyChanged
    {

        private List<Country_MarketsCountry_Market> country_MarketsField;

        private List<Distributor> distributorsField;

        private List<EAN_UPCSEAN_UPC> eAN_UPCSField;

        private List<fileM_Prod_ID> m_Prod_IDField;

        private string pathField;

        private int product_IDField;

        private string updatedField;

        private string date_AddedField;

        private string qualityField;

        private int supplier_idField;

        private string prod_IDField;

        private int catidField;

        private bool on_MarketField;

        private int stockField;

        private bool stockFieldSpecified;

        private string model_NameField;

        private int product_ViewField;

        private string highPicField;

        private int highPicSizeField;

        private bool highPicSizeFieldSpecified;

        private int highPicWidthField;

        private bool highPicWidthFieldSpecified;

        private int highPicHeightField;

        private bool highPicHeightFieldSpecified;

        private int distributor_Info_UpdatedField;

        private bool distributor_Info_UpdatedFieldSpecified;

        public file()
        {
            this.m_Prod_IDField = new List<fileM_Prod_ID>();
            this.eAN_UPCSField = new List<EAN_UPCSEAN_UPC>();
            this.distributorsField = new List<Distributor>();
            this.country_MarketsField = new List<Country_MarketsCountry_Market>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Country_Market", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Country_MarketsCountry_Market> Country_Markets
        {
            get
            {
                return this.country_MarketsField;
            }
            set
            {
                if ((this.country_MarketsField != null))
                {
                    if ((country_MarketsField.Equals(value) != true))
                    {
                        this.country_MarketsField = value;
                        this.OnPropertyChanged("Country_Markets");
                    }
                }
                else
                {
                    this.country_MarketsField = value;
                    this.OnPropertyChanged("Country_Markets");
                }
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<Distributor> Distributors
        {
            get
            {
                return this.distributorsField;
            }
            set
            {
                if ((this.distributorsField != null))
                {
                    if ((distributorsField.Equals(value) != true))
                    {
                        this.distributorsField = value;
                        this.OnPropertyChanged("Distributors");
                    }
                }
                else
                {
                    this.distributorsField = value;
                    this.OnPropertyChanged("Distributors");
                }
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EAN_UPC", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<EAN_UPCSEAN_UPC> EAN_UPCS
        {
            get
            {
                return this.eAN_UPCSField;
            }
            set
            {
                if ((this.eAN_UPCSField != null))
                {
                    if ((eAN_UPCSField.Equals(value) != true))
                    {
                        this.eAN_UPCSField = value;
                        this.OnPropertyChanged("EAN_UPCS");
                    }
                }
                else
                {
                    this.eAN_UPCSField = value;
                    this.OnPropertyChanged("EAN_UPCS");
                }
            }
        }

        public List<fileM_Prod_ID> M_Prod_ID
        {
            get
            {
                return this.m_Prod_IDField;
            }
            set
            {
                if ((this.m_Prod_IDField != null))
                {
                    if ((m_Prod_IDField.Equals(value) != true))
                    {
                        this.m_Prod_IDField = value;
                        this.OnPropertyChanged("M_Prod_ID");
                    }
                }
                else
                {
                    this.m_Prod_IDField = value;
                    this.OnPropertyChanged("M_Prod_ID");
                }
            }
        }

        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                if ((this.pathField != null))
                {
                    if ((pathField.Equals(value) != true))
                    {
                        this.pathField = value;
                        this.OnPropertyChanged("path");
                    }
                }
                else
                {
                    this.pathField = value;
                    this.OnPropertyChanged("path");
                }
            }
        }

        public int Product_ID
        {
            get
            {
                return this.product_IDField;
            }
            set
            {
                if ((product_IDField.Equals(value) != true))
                {
                    this.product_IDField = value;
                    this.OnPropertyChanged("Product_ID");
                }
            }
        }

        public string Updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                if ((this.updatedField != null))
                {
                    if ((updatedField.Equals(value) != true))
                    {
                        this.updatedField = value;
                        this.OnPropertyChanged("Updated");
                    }
                }
                else
                {
                    this.updatedField = value;
                    this.OnPropertyChanged("Updated");
                }
            }
        }

        public string Date_Added
        {
            get
            {
                return this.date_AddedField;
            }
            set
            {
                if ((this.date_AddedField != null))
                {
                    if ((date_AddedField.Equals(value) != true))
                    {
                        this.date_AddedField = value;
                        this.OnPropertyChanged("Date_Added");
                    }
                }
                else
                {
                    this.date_AddedField = value;
                    this.OnPropertyChanged("Date_Added");
                }
            }
        }

        public string Quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                if ((this.qualityField != null))
                {
                    if ((qualityField.Equals(value) != true))
                    {
                        this.qualityField = value;
                        this.OnPropertyChanged("Quality");
                    }
                }
                else
                {
                    this.qualityField = value;
                    this.OnPropertyChanged("Quality");
                }
            }
        }

        public int Supplier_id
        {
            get
            {
                return this.supplier_idField;
            }
            set
            {
                if ((supplier_idField.Equals(value) != true))
                {
                    this.supplier_idField = value;
                    this.OnPropertyChanged("Supplier_id");
                }
            }
        }

        public string Prod_ID
        {
            get
            {
                return this.prod_IDField;
            }
            set
            {
                if ((this.prod_IDField != null))
                {
                    if ((prod_IDField.Equals(value) != true))
                    {
                        this.prod_IDField = value;
                        this.OnPropertyChanged("Prod_ID");
                    }
                }
                else
                {
                    this.prod_IDField = value;
                    this.OnPropertyChanged("Prod_ID");
                }
            }
        }

        public int Catid
        {
            get
            {
                return this.catidField;
            }
            set
            {
                if ((catidField.Equals(value) != true))
                {
                    this.catidField = value;
                    this.OnPropertyChanged("Catid");
                }
            }
        }

        public bool On_Market
        {
            get
            {
                return this.on_MarketField;
            }
            set
            {
                if ((on_MarketField.Equals(value) != true))
                {
                    this.on_MarketField = value;
                    this.OnPropertyChanged("On_Market");
                }
            }
        }

        public int Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                if ((stockField.Equals(value) != true))
                {
                    this.stockField = value;
                    this.OnPropertyChanged("Stock");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StockSpecified
        {
            get
            {
                return this.stockFieldSpecified;
            }
            set
            {
                if ((stockFieldSpecified.Equals(value) != true))
                {
                    this.stockFieldSpecified = value;
                    this.OnPropertyChanged("StockSpecified");
                }
            }
        }

        public string Model_Name
        {
            get
            {
                return this.model_NameField;
            }
            set
            {
                if ((this.model_NameField != null))
                {
                    if ((model_NameField.Equals(value) != true))
                    {
                        this.model_NameField = value;
                        this.OnPropertyChanged("Model_Name");
                    }
                }
                else
                {
                    this.model_NameField = value;
                    this.OnPropertyChanged("Model_Name");
                }
            }
        }

        public int Product_View
        {
            get
            {
                return this.product_ViewField;
            }
            set
            {
                if ((product_ViewField.Equals(value) != true))
                {
                    this.product_ViewField = value;
                    this.OnPropertyChanged("Product_View");
                }
            }
        }

        public string HighPic
        {
            get
            {
                return this.highPicField;
            }
            set
            {
                if ((this.highPicField != null))
                {
                    if ((highPicField.Equals(value) != true))
                    {
                        this.highPicField = value;
                        this.OnPropertyChanged("HighPic");
                    }
                }
                else
                {
                    this.highPicField = value;
                    this.OnPropertyChanged("HighPic");
                }
            }
        }

        public int HighPicSize
        {
            get
            {
                return this.highPicSizeField;
            }
            set
            {
                if ((highPicSizeField.Equals(value) != true))
                {
                    this.highPicSizeField = value;
                    this.OnPropertyChanged("HighPicSize");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighPicSizeSpecified
        {
            get
            {
                return this.highPicSizeFieldSpecified;
            }
            set
            {
                if ((highPicSizeFieldSpecified.Equals(value) != true))
                {
                    this.highPicSizeFieldSpecified = value;
                    this.OnPropertyChanged("HighPicSizeSpecified");
                }
            }
        }

        public int HighPicWidth
        {
            get
            {
                return this.highPicWidthField;
            }
            set
            {
                if ((highPicWidthField.Equals(value) != true))
                {
                    this.highPicWidthField = value;
                    this.OnPropertyChanged("HighPicWidth");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighPicWidthSpecified
        {
            get
            {
                return this.highPicWidthFieldSpecified;
            }
            set
            {
                if ((highPicWidthFieldSpecified.Equals(value) != true))
                {
                    this.highPicWidthFieldSpecified = value;
                    this.OnPropertyChanged("HighPicWidthSpecified");
                }
            }
        }

        public int HighPicHeight
        {
            get
            {
                return this.highPicHeightField;
            }
            set
            {
                if ((highPicHeightField.Equals(value) != true))
                {
                    this.highPicHeightField = value;
                    this.OnPropertyChanged("HighPicHeight");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighPicHeightSpecified
        {
            get
            {
                return this.highPicHeightFieldSpecified;
            }
            set
            {
                if ((highPicHeightFieldSpecified.Equals(value) != true))
                {
                    this.highPicHeightFieldSpecified = value;
                    this.OnPropertyChanged("HighPicHeightSpecified");
                }
            }
        }

        public int Distributor_Info_Updated
        {
            get
            {
                return this.distributor_Info_UpdatedField;
            }
            set
            {
                if ((distributor_Info_UpdatedField.Equals(value) != true))
                {
                    this.distributor_Info_UpdatedField = value;
                    this.OnPropertyChanged("Distributor_Info_Updated");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Distributor_Info_UpdatedSpecified
        {
            get
            {
                return this.distributor_Info_UpdatedFieldSpecified;
            }
            set
            {
                if ((distributor_Info_UpdatedFieldSpecified.Equals(value) != true))
                {
                    this.distributor_Info_UpdatedFieldSpecified = value;
                    this.OnPropertyChanged("Distributor_Info_UpdatedSpecified");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class Country_MarketsCountry_Market : System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class Distributor : System.ComponentModel.INotifyPropertyChanged
    {

        private int idField;

        private bool idFieldSpecified;

        private string nameField;

        private string countryField;

        private string prodlevIdField;

        private string stockField;

        private string updatedField;

        private string eAN_UPCField;

        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.OnPropertyChanged("ID");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                if ((idFieldSpecified.Equals(value) != true))
                {
                    this.idFieldSpecified = value;
                    this.OnPropertyChanged("IDSpecified");
                }
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                if ((this.countryField != null))
                {
                    if ((countryField.Equals(value) != true))
                    {
                        this.countryField = value;
                        this.OnPropertyChanged("Country");
                    }
                }
                else
                {
                    this.countryField = value;
                    this.OnPropertyChanged("Country");
                }
            }
        }

        public string ProdlevId
        {
            get
            {
                return this.prodlevIdField;
            }
            set
            {
                if ((this.prodlevIdField != null))
                {
                    if ((prodlevIdField.Equals(value) != true))
                    {
                        this.prodlevIdField = value;
                        this.OnPropertyChanged("ProdlevId");
                    }
                }
                else
                {
                    this.prodlevIdField = value;
                    this.OnPropertyChanged("ProdlevId");
                }
            }
        }

        public string Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                if ((this.stockField != null))
                {
                    if ((stockField.Equals(value) != true))
                    {
                        this.stockField = value;
                        this.OnPropertyChanged("Stock");
                    }
                }
                else
                {
                    this.stockField = value;
                    this.OnPropertyChanged("Stock");
                }
            }
        }

        public string Updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                if ((this.updatedField != null))
                {
                    if ((updatedField.Equals(value) != true))
                    {
                        this.updatedField = value;
                        this.OnPropertyChanged("Updated");
                    }
                }
                else
                {
                    this.updatedField = value;
                    this.OnPropertyChanged("Updated");
                }
            }
        }

        public string EAN_UPC
        {
            get
            {
                return this.eAN_UPCField;
            }
            set
            {
                if ((this.eAN_UPCField != null))
                {
                    if ((eAN_UPCField.Equals(value) != true))
                    {
                        this.eAN_UPCField = value;
                        this.OnPropertyChanged("EAN_UPC");
                    }
                }
                else
                {
                    this.eAN_UPCField = value;
                    this.OnPropertyChanged("EAN_UPC");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class EAN_UPCSEAN_UPC : System.ComponentModel.INotifyPropertyChanged
    {

        private string valueField;

        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class fileM_Prod_ID : System.ComponentModel.INotifyPropertyChanged
    {

        private string supplier_idField;

        private string supplier_nameField;

        private string valueField;

        public string Supplier_id
        {
            get
            {
                return this.supplier_idField;
            }
            set
            {
                if ((this.supplier_idField != null))
                {
                    if ((supplier_idField.Equals(value) != true))
                    {
                        this.supplier_idField = value;
                        this.OnPropertyChanged("Supplier_id");
                    }
                }
                else
                {
                    this.supplier_idField = value;
                    this.OnPropertyChanged("Supplier_id");
                }
            }
        }

        public string Supplier_name
        {
            get
            {
                return this.supplier_nameField;
            }
            set
            {
                if ((this.supplier_nameField != null))
                {
                    if ((supplier_nameField.Equals(value) != true))
                    {
                        this.supplier_nameField = value;
                        this.OnPropertyChanged("Supplier_name");
                    }
                }
                else
                {
                    this.supplier_nameField = value;
                    this.OnPropertyChanged("Supplier_name");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class EAN_UPCS : System.ComponentModel.INotifyPropertyChanged
    {

        private List<EAN_UPCSEAN_UPC> eAN_UPCField;

        public EAN_UPCS()
        {
            this.eAN_UPCField = new List<EAN_UPCSEAN_UPC>();
        }

        public List<EAN_UPCSEAN_UPC> EAN_UPC
        {
            get
            {
                return this.eAN_UPCField;
            }
            set
            {
                if ((this.eAN_UPCField != null))
                {
                    if ((eAN_UPCField.Equals(value) != true))
                    {
                        this.eAN_UPCField = value;
                        this.OnPropertyChanged("EAN_UPC");
                    }
                }
                else
                {
                    this.eAN_UPCField = value;
                    this.OnPropertyChanged("EAN_UPC");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class Country_Markets : System.ComponentModel.INotifyPropertyChanged
    {

        private List<Country_MarketsCountry_Market> country_MarketField;

        public Country_Markets()
        {
            this.country_MarketField = new List<Country_MarketsCountry_Market>();
        }

        public List<Country_MarketsCountry_Market> Country_Market
        {
            get
            {
                return this.country_MarketField;
            }
            set
            {
                if ((this.country_MarketField != null))
                {
                    if ((country_MarketField.Equals(value) != true))
                    {
                        this.country_MarketField = value;
                        this.OnPropertyChanged("Country_Market");
                    }
                }
                else
                {
                    this.country_MarketField = value;
                    this.OnPropertyChanged("Country_Market");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class Distributors : System.ComponentModel.INotifyPropertyChanged
    {

        private List<Distributor> distributorField;

        public Distributors()
        {
            this.distributorField = new List<Distributor>();
        }

        public List<Distributor> Distributor
        {
            get
            {
                return this.distributorField;
            }
            set
            {
                if ((this.distributorField != null))
                {
                    if ((distributorField.Equals(value) != true))
                    {
                        this.distributorField = value;
                        this.OnPropertyChanged("Distributor");
                    }
                }
                else
                {
                    this.distributorField = value;
                    this.OnPropertyChanged("Distributor");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
